[package]
name = "fetter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fetter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
fetter = "0.3.1"
